In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[4, 9]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[12, 19], [4, 9], [20, 28], [14, 14, 18], [9, 7, 2], [21, 19], [23, 7, 29], [23, 1], [23, 7], [11, 22]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews) #towards the end

[[12 19  0  0]
 [ 4  9  0  0]
 [20 28  0  0]
 [14 14 18  0]
 [ 9  7  2  0]
 [21 19  0  0]
 [23  7 29  0]
 [23  1  0  0]
 [23  7  0  0]
 [11 22  0  0]]


In [5]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [6]:
X = padded_reviews
y = sentiment

In [16]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.build(input_shape=(None, max_length))
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 4, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 171 (684.00 B)

 Trainable params: 171 (684.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [17]:
model.fit(X, y, epochs=50, verbose=0)

In [9]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - accuracy: 1.0000 - loss: 0.6281


1.0

In [21]:
import pandas as pd
# Displaying the full 30x5 weight matrix
weights_df = pd.DataFrame(weights)
weights_df

,0,1,2,3,4
0,-0.016195,0.054487,0.008474,0.005577,0.052759
1,-0.093999,-0.060724,0.105693,0.105013,0.074622
2,-0.135996,-0.090626,-0.103777,-0.066528,-0.106743
3,-0.015567,0.026916,0.004612,0.030878,0.008474
4,-0.129437,0.142789,-0.059532,0.116097,-0.147117
5,-0.014678,-0.011663,-0.010133,-0.034838,0.035970
6,0.048790,0.040837,-0.038184,0.022169,-0.046523
7,-0.100991,-0.074750,0.009240,0.095007,0.012584
8,0.037314,0.049010,-0.022546,0.031968,-0.015309
9,-0.059251,0.130680,-0.162295,-0.073892,-0.121762


In [11]:
weights[13]

array([-0.02060199,  0.00143472,  0.0189434 , -0.02053558,  0.04436267],
      dtype=float32)

In [12]:
weights[4]

array([-0.07941911,  0.09211389, -0.00864497,  0.06479321, -0.09370852],
      dtype=float32)

In [13]:
weights[16]

array([ 0.04344347,  0.00892013,  0.04229666, -0.04256879,  0.03561895],
      dtype=float32)